### ISSUE TITLE
Lost of perspective when navigating

### ISSUE THREAD

**Issue by ericpallares** [BCN3D/Cura#1]
When panning, orbiting and zooming in/out, sometimes I totally lose the perspective. When that happens, it turns out the viewpoint is completely zoomed in and I can't zoom out at all. Therefore, it's needed to shut down Cura an open it again.

**Comment by ChrisTerBeke** [comment]
https://github.com/Ultimaker/Cura/commit/3f903d2c76fd2540cfcdb81017b47d52af43f908 ;)

**Comment by eloipr** [comment]
Thanks @ChrisTerBeke.
Very useful feature that can solve the problem! :smiley:
