### ISSUE TITLE
Printing Temperature Initial Layer issue

### ISSUE THREAD

**Issue by v-iarosenco** [BCN3D/Cura#10]
0 value for "Printing Temperature Initial Layer" actually makes printing temp. 5 degrees lower.
If set to the same temp. as "Default Printing Temperature" e.g. 235 for both, generates correct results.
Auto Temperature is ON

**Comment by guillemavila** [comment]
This is the normal behavior of the Cura Engine.
When `Printing Temperature Initial Layer` is set to 0 the engine heats the hotend to the `Prinitng Temperature` value. (The visibility of this value is hidden if `Auto Temperature` is enabled).

Other values greater than 0 for `Printing Temperature Initial Layer` heat the hotend to that value.

Thanks
