### ISSUE TITLE
Manual Temperature overrides not recognized

### ISSUE THREAD

**Issue by Sigma1912** [BCN3D/Cura#128]
**Application Version**

2.1.3 & 2.1.4
**Platform**

Linux & Windows
**Qt**

**PyQt**

**Display Driver**

**Steps to Reproduce**

Change Hotend temperatures in Cure custom settings
**Actual Results**

The custom temperature settings are not put into the gcode.
**Expected results**

**Additional Information**

**Comment by v-iarosenco** [comment]
I don't see a reason for closing the issue - it's the same in 2.1.5 - I manually set PETG temperature in every possible place and it's still 223!
