### ISSUE TITLE
problem about bcn3d cura1.0

### ISSUE THREAD

**Issue by yuchu3d** [BCN3D/Cura#13]
if i select the sigmax in bcn3d cura1.0, it just unable to slice and report errors.

**Comment by eloipr** [comment]
Download again the [installer](https://drive.google.com/file/d/0B9EhngnR5bl6N1Q1cXFzTkpfazQ/view), this issue should be fixed.
Also delete the these folders:
C:\Users<user_name>\AppData\Roaming\BCN3D Cura
C:\Users<user_name>\AppData\Local\BCN3D Cura

**Comment by yuchu3d** [comment]
i am sorry. i forgot that,  but it is be closed now i think.






------------------
Name: Yuchu Huang
Tel: 13553538492
Adress: Shiqiao street Dongxing path the number of 476 in Canton city Guangdong province (广东省广州市番禺区市桥街东兴路476
 号星海通信息文化产业园）
 

 
 
 
------------------ Original ------------------
