### ISSUE TITLE
Cura builds infill below roof...

### ISSUE THREAD

**Issue by S3D-r** [BCN3D/Cura#145]
-->

**Application Version**

2.1.5
**Actual Results**

Infill layer will be built (layer 11) below the roof of a horizontal hole

**Expected results**

Roof directly on the top of the hole, no infill layer.

https://youtu.be/MbUM3GSqMG0

**Comment by S3D-r** [comment]
For some reason, Github fails to create a correct hyperlink, another try https://youtu.be/MbUM3GSqMG0

**Comment by eloipr** [comment]
This is fixed in future versions of ultimaker cura and in the next releases we are not planning to fix it.

**Comment by S3D-r** [comment]
So, you have reported this to Ultimaker, right? Have they told that it will be fixed or is it just your humble wish... :-) ?

**Comment by eloipr** [comment]
Sorry, I think I haven't explained myself well. We haven't reported it. The last Cura version doesn't have this issue, but BCN3D Cura is based on Cura 3.2 (which has the issue). 
Upgrading is a huge amount of work and it's not going to happen soon.

**Comment by S3D-r** [comment]
Now that's an accurate and clear answer.

**Comment by S3D-r** [comment]
I still wish that each issue would get a flag that it deserves. In this case, I guess the tag would be "a bug".
