### ISSUE TITLE
Dual color print issue

### ISSUE THREAD

**Issue by cyclemadkiwi** [BCN3D/Cura#15]
Just started a dual color print with ABS in both extruders, the first extruder (T0) did the correct temp for the skirt and first layer, but when T1 came out it did the skirt and first layer 10°C lower than it was told to in Cura. the rest of the layers were all at the correct temp! The M109 commands in the first layers for T1 are not correct. Auto Temp was turned off.

**Comment by guillemavila** [comment]
We are not having this issue... Just uploaded the[ installer 1.0.2](https://github.com/BCN3D/Cura/releases/tag/v1.0.2-beta) which solves almost all issues reported until now, you can test it and if everything is solved I'll close the issue.

_As we are upgrading between beta releases it's recommended to delete these folders:
C:\Users<user_name>\AppData\Roaming\BCN3D Cura
C:\Users<user_name>\AppData\Local\BCN3D Cura_

**Comment by cyclemadkiwi** [comment]
I have been using the 1.0.2 since Eloipr sent me some fixes....all seems to be working really well....just started a 42 hour dual print on my Sigma :-)

**Comment by guillemavila** [comment]
Awesome, new version with more corrections available!

(Not needed to remove these folders manually anymore)
