### ISSUE TITLE
Enfriamiento de los hotends al inicio de la impresión

### ISSUE THREAD

**Issue by Marcramoscosta** [BCN3D/Cura#16]
El cura al inicio del Gcode genera estas instrucciones:

;BCN3D_FIXES
;Generated with Cura_SteamEngine 1.0.1-beta
M190 S65                 
M104 S220               
M104 T1 S220
M109 S220
M109 T1 S220

Primero calienta cama pero hasta que esta no alcanza los 65º las temperaturas de los hotends es por defecto 0º con lo que se enfrían. Una vez llega a los 65º empieza a calentar los hotends.

El problema viene cuando haces preheat y pone a imprimir la pieza pero la cama todavía no las has precalentado lo suficiente. Esto hace que a pesar de tener los hotends a la temperatura adecuada estos bajan mientras la cama se calienta. Como la cama tarda más en calentar o enfriar que los hotends, se pierde la función esencial del preheat (si es que no ha llegado la cama a la temperatura antes de poner a imprimir).

Si se invierte el orden de los comandos y se fijan así:

;BCN3D_FIXES
;Generated with Cura_SteamEngine 1.0.1-beta                
M104 S220               
M104 T1 S220
M109 S220
M109 T1 S220
M190 S65 

se evita este pequeño bug de enfriamiento/calientamiento de los hotends. Ya que antes de hacerle set a la temperatura de la cama, haces set a la temperatura de los hotends (los cuales son más rápidos de calentar).

Se ha realizado una prueba y efectivamente funciona correctamente.

**Comment by guillemavila** [comment]
La secuencia de calentamiento inicial está diseñada así intencionalmente por motivos de seguridad, fiabilidad y funcionamiento de la máquina.

Primero se calienta la cama que es lo más lento, y luego los hotends que son mucho más rápidos. 

Así se evita tener los hotends sobrecalentando el material durante todo el proceso de calentamiento de la cama, lo cual puede producir obturaciones en los hotends para determinadas combinaciones de material-temperatura-tiempo de espera.

_**Sujeto a consecuencias**, un 'truquillo': En caso de no querer esperar a que la cama alcance la temperatura, y que empieze rápido a calentar los hotends, se puede iniciar la impresión, seguidamente ir a settings, bajar la temperatura objetivo de la cama a una temperatura inferior a la actual (aquí dará la orden de calentar los Hotends), y luego volver a subirla hasta la temperatura objetivo deseada.
Esto hará que la impresión empieze cuando los hotends alcancen la temperatura, independientemente de la temperatura de la cama, la cual irá subiendo hasta su temperatura objetivo durante la impresión.
Importante tener en cuenta las consecuencias de falta de adhesión que puede comportar implementar este proceso._
