### ISSUE TITLE
Profiles lost

### ISSUE THREAD

**Issue by v-iarosenco** [BCN3D/Cura#18]
Printing profiles have lost after the latest Windows update.
Re-install didn't help, still can't see profiles. 
Materials are fine, even the customized ones.

**Comment by eloipr** [comment]
Close Cura and then try deleting these folders:
C:\Users\<userName>\AppData\Local\Bcn3D Cura
C:\Users\<userName>\AppData\Roaming\Bcn3D Cura

**Comment by v-iarosenco** [comment]
I did, it worked. I thought it could be something for BCN to change in the final version, so no one experience it again...

**Comment by ianewby** [comment]
I have a related issue- the profiles disappear if I change the nozzle size. Even if I change it back, they are not there.
