### ISSUE TITLE
Overhang angle issue

### ISSUE THREAD

**Issue by v-iarosenco** [BCN3D/Cura#19]
Printing a pyramid with 120 deg at the top, which means the angle between the bed and inclined side is 30 deg, managed to get rid of support only setting "support overhang angle" to 80 deg. 
I understand the support won't be used by setting it to 35. Confusing and seems to work incorrectly.

**Comment by guillemavila** [comment]
When setting **Support Overhang Angle** you set the minimum vertical angle of overhangs for which support is added. At a value of 0° all overhangs are supported, 90° will not provide any support.

For your case I understand the pyramid brace has a 60º vertical angle, and a 30º horizontal angle.
Then setting a value greater than 60 for Support Overhang Angle won't generate support.
