### ISSUE TITLE
Wall Thickness Count

### ISSUE THREAD

**Issue by cyclemadkiwi** [BCN3D/Cura#21]
Under the "Shell" options the "wall line count" is incorrectly set
When you are using a 0.4mm nozzle wall thickness is 1.2mm the "_Calculated_" Wall line count is displayed as "4" if you manually set wall thickness to 1.2 it updates the wall line count to 3, which is then correct.

This happens with all nozzle sizes

**Comment by guillemavila** [comment]
Solved for the new profiles, thanks!
