### ISSUE TITLE
Infill shows always the same in preview

### ISSUE THREAD

**Issue by S3D-r** [BCN3D/Cura#23]
Print preview shows the infill always the same, no matter the % is. Here I have 100% infill, and the infill (brown color) looks exactly same with 40% or 80% etc...

![image](https://user-images.githubusercontent.com/19798034/32465678-f58b6084-c34c-11e7-8ccf-8f14cadc3b0e.png)

**Comment by eloipr** [comment]
Have you done the slice again?
When a setting is changed, a slice is needed in order to preview it in the layer view mode.

**Comment by S3D-r** [comment]
Hi!

Cura performs the slicing automatically after any change, and so did it in this case (it took <10 sec.). Before taking the screen shot, I wait until the slicing had finished. I made about five tests with different infill.

However, I today opened the same project file, and the infill view had changed, and now it looks as it's supposed to (with different infill %'s)!  

It was a late evening yesterday , Cura may have been tired and it refused to do its job and it just needed to sleep over night!  ;-)    Next time in similar case I try rebooting Cura and/or reboot PC.
