### ISSUE TITLE
Unexpected travel to specific X/Y coordinates

### ISSUE THREAD

**Issue by cyclemadkiwi** [BCN3D/Cura#24]
Left head ASA Right head HIPS for support, standby temp set at 150°C
Smart Purge turned off.
the first 8 layers at every layer, the right head moves to X0.0 Y210 (Guess, middle rear of table) after each completed layer of the left head, no support was required at this stage, the right extruder sat at full temp (250°C) for the entire print, not once dropping to standby temp.
It continues to do this even after going above Z height where no support was required or existed in the layers view in Cura.

**Comment by cyclemadkiwi** [comment]
today it works ok! maybe a setting wrong :-(
Cura put some support in odd place, 5 identical parts placed at identical spacing but the odd squirt of support only on 2 parts. otherwise the right extruder is now going to standby temp.

**Comment by svengl** [comment]
Same issue here. Right extrudes moves to the rear center and does nothing, then goes back to the stop.

**Comment by guillemavila** [comment]
Is it happening with the latest version?

https://github.com/BCN3D/Cura/releases/tag/v1.0.3

**Comment by cyclemadkiwi** [comment]
Yes, it is with 1.0.3

**Comment by maodch** [comment]
Got the same issue. Might be the primetower position, even there isn't one. 
like going to prime ... ohhh damn, there is no prime tower set ... going to purge tray instead :-)

**Comment by svengl** [comment]
Yes happens with 1.0.3

**Comment by guillemavila** [comment]
It uses to happen to us traveling to the point (`layer start X`, `layer start Y`). But we are actually fixing this unexpected travel.

Do you have some parameter pointing to those X/Y coordinates? (0, 210) in your case.

**Comment by guillemavila** [comment]
Issue name changed for better order

**Comment by svengl** [comment]
I couldn't reproduce it yet with other dual extrusion prints. So it is not
always.

Am 20.12.2017 19:59 schrieb "Guillem" <notifications@github.com>:

**Comment by guillemavila** [comment]
Fixed https://github.com/BCN3D/Cura/commit/f2990a9554e493b2c7723d0e4cc2744c67b4b549
