### ISSUE TITLE
Right Extruder printing in the Air without extruding.

### ISSUE THREAD

**Issue by svengl** [BCN3D/Cura#25]
This is an awkward issue. The right extruder for the support moves to the correct position, where the support should be, and then moves quite fast over where it should print the support, but it doesnt extrude anything. After that, it slows down and extrudes.

**Comment by guillemavila** [comment]
Can you upload the gcode?
Thanks for testing

**Comment by svengl** [comment]
I just see that I  accidentally deleted it. It was also with the 1.0 beta. I will see if I can reproduce with 1.0.3 and how. Then I will let you know. 
Sorry for the inconvenience

**Comment by guillemavila** [comment]
Ok, thanks for reporting
