### ISSUE TITLE
Skirt not going around all parts

### ISSUE THREAD

**Issue by WanaGo** [BCN3D/Cura#28]
I have noticed this a few times now. The skirt does not always go around all the parts, but can cut through some, like in this example.

![image](https://user-images.githubusercontent.com/200210/32818067-f561cdca-ca25-11e7-8480-a66d788d8f81.png)

Unsure what is causing it

Model from here: https://makeprintable.com/printables/download/586e24e2d13f4a6dda5bd7a9

Regards

**Comment by eloipr** [comment]
![screenshot from 2017-11-15 10-36-46](https://user-images.githubusercontent.com/20399548/32828959-f137b244-c9f0-11e7-9613-2b8d83781a98.png)

The first layer of the sheep legs are not touching the platform. 
Enabling support or translating the model to Z -1 fixes the problem.

**Comment by WanaGo** [comment]
Ah, yes you are right. Also flipping it over 180 does the trick. the other side is flush. Seems the legs are a fraction shorter than the body, and it imported upside down. Thanks
