### ISSUE TITLE
Temperatures on dual material print incorrect

### ISSUE THREAD

**Issue by ianewby** [BCN3D/Cura#29]
BCN Cura 1.0.2-Beta
I have tried a dual print with Ultimaker PVA in extruder 1,  Colourfabb XT in extruder 2, Setting support to extruder 1. The print starts successfully, however the temperatures soon drop and the print fails.
Looking in the gcode  we get

M109 S220
M109 T1 S260 

which is what I expect near the beginning, then after the first layer at the beginning of every layer for extruder 1: 

T0
G92 E0
G91
G1 F12000 Z2
G90

M109 S220.0

And for Extruder 2:

T1
G92 E0
G91
G1 F12000 Z2
G90

M109 S220.0

It looks like the print temperature is being set always to the first extruder temperature?

**Comment by eloipr** [comment]
This issue should be fixed in the latest release.
Download it from the [web](https://www.bcn3dtechnologies.com/en/3d-printer/bcn3d-cura/).
