### ISSUE TITLE
Adding materials breaks profiles

### ISSUE THREAD

**Issue by ianewby** [BCN3D/Cura#30]
Latest BCN3D Cura 1.0.3 Win 64.

If you add new materials to the materials section, then change nozzle size the profiles all vanish.

**Comment by maodch** [comment]
Got the same, but if you switch to a built in Material, all settings come back.
And it's randomly, some user-materials are working well, others not. I couldn't find out what's the problem.
I compared every setting from the worting to the "profile-killing-one", but without success.

**Comment by cyclemadkiwi** [comment]
yes, I have also opened issue with this! twice in fact

**Comment by eloipr** [comment]
There was a code error when creating the material.
It has been fixed and will be available in the next release.
