### ISSUE TITLE
display errors

### ISSUE THREAD

**Issue by hst68** [BCN3D/Cura#31]
In the current version 1.03 for macOS 10.13 there are display errors. See attachment
![screenshot at nov 16 18-34-39](https://user-images.githubusercontent.com/32851794/32906496-4c78e4f4-cafd-11e7-835f-b35a1c9367ed.png)

**Comment by hst68** [comment]
![screenshot at nov 16 19-13-26](https://user-images.githubusercontent.com/32851794/32907974-5eab509e-cb02-11e7-86c9-ed4bb68c4432.png)

**Comment by hst68** [comment]
My Solution:
Go to Applications > Font Book and doing File > Restore Standard Fonts and restarting.

You could also try to clean the font cache:
Terminal
sudo atsutil databases -remove

**Comment by eloipr** [comment]
Thanks for sharing the solution!

**Comment by hst68** [comment]
unfortunately the problem persists partially

**Comment by eloipr** [comment]
I've also experienced this problem using cura in a virtual machine. Don't know what can be causing it.

**Comment by atlemo** [comment]
This is a known issue with Cura, apparently:
https://ultimaker.com/en/community/51334-cura-fonts-garbled-on-macos-high-sierra

**Comment by guillemavila** [comment]
Fixed b4b7691b44e01dd600382754e41b07892d0b1cd1
