### ISSUE TITLE
Extruder does not align with build plate (mid-air printing)

### ISSUE THREAD

**Issue by atlemo** [BCN3D/Cura#34]
Gcode here: https://cl.ly/0K0o2d1U3b40

It starts printing with the Right extruder 1cm above the build plate, even after a fresh calibration.
I tried to enable and disable "Z Hop When Retracted", no difference.

Running BCN3D Cura v1.0.3, macOS 10.13.1 (17B48)

Might be related to Bug 25.

**Comment by guillemavila** [comment]
Fixed for the next release! Thanks ;) 10504086f5bb42276abe0e70e60cd9d96712a0ff
