### ISSUE TITLE
Hotends do not purge & Hotends do not cool down.

### ISSUE THREAD

**Issue by axiiiofevil** [BCN3D/Cura#37]
This version 1.0.3 (by default it seems) is set to print a tower. I turned this off and the following things occurred.
1. The left extruder which is set to PLA is no longer purging before printing.
2. I don't think that the right extruder is purging either, but it's hard to see as this hotend is printing PVA which oozes LOTS.
3. I switched on smartpurge in both extruders so that it would purge before printing. Now both extruders purge, but the temprature does not ramp down to the default 150 degrees when the hotend is not printing.

**Comment by guillemavila** [comment]
> The left extruder which is set to PLA is no longer purging before printing.

> I don't think that the right extruder is purging either, but it's hard to see as this hotend is printing PVA which oozes LOTS.

Yes, the purge is intended to be done in the tower. PVA is also not purging but maybe its natural ooze is confusing.

> I switched on smartpurge in both extruders so that it would purge before printing. Now both extruders purge, but the temprature does not ramp down to the default 150 degrees when the hotend is not printing.

Good. Note the hotend will go to standby temperature only if it's going to be idle for more than 5mins. If it's idle for more than 5mins and the temperature is not going down, then it's a [known bug](https://github.com/BCN3D/Cura/issues/26#issuecomment-344930629) we're working on.
