### ISSUE TITLE
Feature Request: Firmware Update for Mac Version

### ISSUE THREAD

**Issue by mawesigma** [BCN3D/Cura#39]
Hello dear Project Team

It would be great to have the possibility to update the Sigma-Firmware with the Mac Version of CURA_BCN3D. I found some HowTo's, but they are for the Windows Version only.
I hope I didn't miss a wiki in which this missing feature is already explained/discussed.

Greetings

**Comment by eloipr** [comment]
We are working on it for the next release!!!

**Comment by guillemavila** [comment]
Solved https://github.com/BCN3D/Cura/commit/5bc2b07bd5dc9acb06def5ec45e811e3980a44df
