### ISSUE TITLE
Cura swaps left and right temperature settings?

### ISSUE THREAD

**Issue by S3D-r** [BCN3D/Cura#43]
I'm printing with the LEFT. 

Printing starts at 225C, but at some point (didn't follow, 12 hours print) goes down to 207C.  It may be so, that the Left Extruder temperatures are (incorrectly) taken from right extruder settings and vice versa. Similar problems occurred with right extruder (see my earlier topic 11 days ago). I haven't done systematic tests, this is just a quick observation.

**LEFT** Extruder:
![image](https://user-images.githubusercontent.com/19798034/33978523-d7ddb0fe-e0a8-11e7-9040-d7e6cf5d8479.png)

**RIGHT** Extruder:
![image](https://user-images.githubusercontent.com/19798034/33978810-22595790-e0aa-11e7-8d99-0f075f655a48.png)

**Comment by guillemavila** [comment]
Can you upload the gcode?
Thanks

**Comment by S3D-r** [comment]
Here you are:  

https://www.dropbox.com/s/9cwdcbvgwh6yqy2/Temperature%20problem.gcode?dl=0
