### ISSUE TITLE
Cura for Mac 1.1.0 Beta "BCN3D Cura" is damaged and can not be opened. You must eject the disk image.

### ISSUE THREAD

**Issue by flandaluce** [BCN3D/Cura#48]
Intentando instalar la última versión de Cura para Mac
===============
“BCN3D Cura” está dañado y no puede abrirse. Debe expulsar la imagen de disco.
“BCN3D Cura” está en la imagen de disco “BCN3D.Cura-1.1.0-beta.dmg”. Safari descargó esta imagen de disco hoy a las 17:40 desde github.com.
===================
Descargado varias veces alguna idea?
Trying to install the latest version of Cura for Mac
===============
"BCN3D Cura" is damaged and can not be opened. You must eject the disk image.
"BCN3D Cura" is in the disk image "BCN3D.Cura-1.1.0-beta.dmg". Safari downloaded this disk image today at 17:40 from github.com.
===================
Unloaded several times some idea?

**Comment by eloipr** [comment]
I have updated the file.
Download it again from the release.

**Comment by eloipr** [comment]
Write in the terminal:
`sudo spctl --master-disable`
This will let you install non Apple apps.

**Comment by flandaluce** [comment]
Works, thanks
