### ISSUE TITLE
Can't slice with layerheight above 0.3mm with 0.8mm Nozzle

### ISSUE THREAD

**Issue by maodch** [BCN3D/Cura#49]
Hi there

how to setup, printing with 0.8mm nozzle and layerheight more than 0.3mm?
Should it not be possible to have left 0.8 and right 0.5mm for combining materials?
I tried some settings, but getting every time the "unable to slice" error.

Any idea?

**Comment by guillemavila** [comment]
Sorry for the late response, you may have a hotend with a smaller nozzle in the other extruder which is not capable of printing at 0.4 layer height. Change to a 0.8 hotend and it will enable slicing again.
