### ISSUE TITLE
1.1.0 Beta - Error on Install Mac

### ISSUE THREAD

**Issue by ZAMHelmets** [BCN3D/Cura#50]
I get a "BCN3D Cura.app" is damaged and can't be opened. You should eject the disk image message.

Downloaded twice (once when the Beta was made available and again today) and get the same error both times.
![_volumes_bcn3d_cura](https://user-images.githubusercontent.com/9206926/34513582-c59a2272-f01d-11e7-84b0-2fef3b99c4da.png)

**Comment by eloipr** [comment]
[https://github.com/BCN3D/Cura/issues/48#issuecomment-354240370](https://github.com/BCN3D/Cura/issues/48#issuecomment-354240370)

**Comment by ZAMHelmets** [comment]
Thanks and apologies - had filters on in GitHub and didn't see the solution previously.
