### ISSUE TITLE
Grouping issue

### ISSUE THREAD

**Issue by cyclemadkiwi** [BCN3D/Cura#54]
When I select "Multiply Selected Model" and make copies....I group them to move them and I get the group moving to random location on it own. Try to move them manually and when you release the mouse button them move back to where you moved them from!

**Comment by eloipr** [comment]
For me it is working fine.
Is this happening when using duplication/mirror mode or regular mode?

**Comment by cyclemadkiwi** [comment]
​This was in regular mode! I just tested and it works fine! Maybe I did
something wrong before, my friend Carl also had same issue....I think it
was an error we made. Before I can try it again (The 1.1.0 Beta) the Nozzle
Temp issue will need fixing....keep up the great work :-)

Regards
Glen​

**Comment by eloipr** [comment]
Thanks for your feedback, we'll check the Nozzle Temp issue you've mentioned. :D
