### ISSUE TITLE
Bug: 2nd Extruder does not do a Smart Purge if used for supports

### ISSUE THREAD

**Issue by ZAMHelmets** [BCN3D/Cura#57]
Even if both extruders are set to use smart purges, the 2nd Extruder does not do any purges prior to printing if it is only used for support (i.e. no objects in the project are assigned to it). This seems like one of the primary use cases for duel extruders (one primary material, second for support) so I'm assuming this is a bug. Thank you.

**Comment by guillemavila** [comment]
Solved in [Cura 2.0](https://github.com/BCN3D/Cura/releases/tag/v2.0.0-alpha)
