### ISSUE TITLE
T1 Fix issue

### ISSUE THREAD

**Issue by MJFX-645** [BCN3D/Cura#59]
I noticed a priming issue when using the right extruder (dual prints and using right extruder only)

Looking through the gcode on a right extruder only print I found this

;LAYER_COUNT:19
;LAYER:0
G1 F2100 E-16
G92 E0

T1
G92 E-8.0 ;T1fix
G91
G1 F12000 Z5
G90

The T1 fix value is incorrect and should be set to E-16.0 due to the extra retract in the ;LAYER:0 section 
or the extra retraction in ;LAYER:0 section should be removed

When I edit the gcode manually and either comment out "G1 F2100 E-16" or change the T1fix value to "E-16.0" I get a successful print.

**Comment by guillemavila** [comment]
Fixed in Cura 2.0
