### ISSUE TITLE
BCN3Dcura 2.0.0 alpha: Create material button does nothing

### ISSUE THREAD

**Issue by sk4477** [BCN3D/Cura#63]
I cannot create a new material from scratch. Clicking the create material button does nothing. Duplication works normal. 
System affected: BCN3D_cura 2.0.0 alpha running on Win10. 
![2018-03-09_11h49_52](https://user-images.githubusercontent.com/37211864/37204055-10229c8e-2390-11e8-9856-027653217c7e.png)

**Comment by sk4477** [comment]
This bug is still around in 2.0.0 beta
(and apparently it is also in Cura 3.2.1)

**Comment by eloipr** [comment]
When you click the "Create" button, the new material is created under ther "Custom" category. You have to scroll down and you'll see it.

**Comment by sk4477** [comment]
I wish.. But it doesn't. No custom material category is created, no new material added. 
See https://github.com/Ultimaker/Cura/issues/3367

But: since it is an UltiMaker Cura issue, i guess i better join the thread there. 
Thanks anyway

**Comment by guillemavila** [comment]
Fixed with [v2.0.1](https://github.com/BCN3D/Cura/releases/tag/v2.0.1)?

**Comment by sk4477** [comment]
Yes, appears to be fixed. Installed 2.0.1, deleting both appdata folders, problem can no longer be recreated. Is working now as intended.
