### ISSUE TITLE
BCN3D Cura 2.0Alpha Stuttering from massive repetition of M205 M204 

### ISSUE THREAD

**Issue by Neotko** [BCN3D/Cura#64]
Been seeing a weird amount of blops on certain curve moments and at first though was the planner but after checking the gcode clearly there's a small bug adding tons of M204 M205 with the same specific speed over and over, that most certainly could be the stuttering issue since it's collapsing the planner moves

<img width="716" alt="cura2 0alpha" src="https://user-images.githubusercontent.com/11388374/37240720-85b6179a-244f-11e8-98c2-4bb229981cc3.png">

Search this sequence

M204 S2000
M205 X15 Y15
M204 S1155
M205 X11.25 Y11.25

= 3862 times and everytime on packs like the image. Basically it's doing one speed and then changing it again. That also can't be good for the planner buffer

I upload the gcode. It's done using this model Normal quality + Experimental adaptive layer height + auto temperature, no other changes done

[S_PorgPLAPVA-Adaptive-test.gcode.zip](https://github.com/BCN3D/Cura/files/1799245/S_PorgPLAPVA-Adaptive-test.gcode.zip)

**Comment by guillemavila** [comment]
Fixed https://github.com/BCN3D/Cura/commit/8d720d417be0584fa9937a943c32b9f186aff991
