### ISSUE TITLE
Speed print quality text are in reverse

### ISSUE THREAD

**Issue by Neotko** [BCN3D/Cura#65]
<img width="444" alt="captura de pantalla 2018-03-10 a las 20 23 49" src="https://user-images.githubusercontent.com/11388374/37245979-0fffe420-24a1-11e8-9f00-5ef824fc1ffc.png">

The 0.2 says 'Slower' where it should be faster and 0.08 says faster where it should be slower 💃

**Comment by guillemavila** [comment]
Fixed https://github.com/BCN3D/BCN3DSigma-Profile-Generator/commit/102c3ecaca219625d20af0676e64b880e311eb98
