### ISSUE TITLE
Cura 2 Alpha Fails to import or create profiles

### ISSUE THREAD

**Issue by cyclemadkiwi** [BCN3D/Cura#69]
Material profiles import just fine, but when I import a profile from Ver1.1 it tells me success but it's nowhere to be seen. I use an included profile and adjust it to my material settings and select "Make new profile from current settings" and it says it created successfully but again it's nowhere to be seen! 

This was an issue in earlier version, it seems to have come back....hope this can be looked at and fixed very soon.

**Comment by guillemavila** [comment]
Sigma/Sigmax old profiles import fixed https://github.com/BCN3D/Cura/commit/0092856e025dfeeed04429446d6a6ca5a27a361f
