### ISSUE TITLE
Dual Color print- Crash tool head at first color change

### ISSUE THREAD

**Issue by cyclemadkiwi** [BCN3D/Cura#7]
[classic_cone_Check Code Cura 1.0.0.zip](https://github.com/BCN3D/Cura/files/1385905/classic_cone_Check.Code.Cura.1.0.0.zip)
Printed a simple 2 color cone, it did the first skirt and layer 1 for first color, did tool change and skirt for second head. Tool change to first tool head again and prints to Z 10.2, then tool change to second color and moves over the job, rapids to Z0.2.....Boom Crash!!! Print does tool head change at layer 50.

Reading the code it looks to be trying to do a whole new first layer. 442 lines later it comes to layer 51 and moves the head height to Z10.2 which is correct. 

This is a BIG ERROR!!!!

**Comment by cyclemadkiwi** [comment]
After looking at all the code......every time it changes the tool Head it takes the nozzle to Z0.2 another 440 lines of walls and skin before getting back to the correct Z height. Crash at every color change. I also did a multi color Draudi (Puzzle _Draudi) and as it has both colors at each layer this error did not occur!

**Comment by guillemavila** [comment]
Fixed. Thanks!
