### ISSUE TITLE
limit to layer heights

### ISSUE THREAD

**Issue by cyclemadkiwi** [BCN3D/Cura#70]
With each size nozzle, you can't select more than 0.3mm layer heights!!!

For each nozzle size you should be able to select up to at least 70% layer height of the current nozzle diameter. Now that we have adaptive layers and able to use big nozzle for infill then we should be able to select layer heights according to the diameter of the nozzle.

I want to do a fast "Draft" model of a part that has straight sides and not much details. I want to use a large nozzle size and bigger layer height to save time before making high quality part. I cannot go past 0.3mm layer!

**Comment by guillemavila** [comment]
I guess this is because you have a 0.4mm nozzle on the other extruder. Then 0.3 is 75% of 0.4
