### ISSUE TITLE
"Laptop not connecting"

### ISSUE THREAD

**Issue by datintac** [BCN3D/Cura#71]
I am having difficulty interacting with my sigma printer through my laptop.

**Comment by guillemavila** [comment]
Are you connecting to the machine over USB?
Trying to upgrade Sigma's firmware?

**Comment by datintac** [comment]
yes

Denise Thompson

Orting High School STEM Teacher
STEM club advisor
OEA Co- President

“Confusion is a sign that LEARNING is about to take place”

**Comment by guillemavila** [comment]
This issues page is intended to solve software-specific bugs and feature requests. 

As it seems it's a very specific issue I suggest you to contact our tech support at sat@bcn3dtechnologies.com as they will give you the best personal advice on how to fix it.

If after that we find out it's a general issue I'll reopen this issue and post the solution so everyone can check it out.

Thanks for reporting Denise
