### ISSUE TITLE
Not enough material ready

### ISSUE THREAD

**Issue by maodch** [BCN3D/Cura#74]
In the latest version it's impossible to print something, because at the begining of each cycle (skirt, part, tower what ever), the filament comes very late and with to few dense out the nozzle.

With Sigma it's unusable. Did you change something with the feedrade (maybe took the one for sigmax (bondtech) instead the sigma (non bondtech).

I downgraded the version to 1.1 (BCN edition) and also tired the original cura fom Ultimaker without having this problems.

**Comment by guillemavila** [comment]
Hmm.. strange, as coast/wipe settings are the same in 2.0 and 1.1
Do you have the failing gcodes so we can check them?

**Comment by guillemavila** [comment]
Same issue as https://github.com/BCN3D/Cura/issues/85 ?
