### ISSUE TITLE
Make the "Build Plate Adhesion Extruder" "Not overridden" by Default

### ISSUE THREAD

**Issue by thesec** [BCN3D/Cura#79]
The extruder for build plate adhesion should be the currently selected by default, please add the "Not overridden" selection to this option and make it the default to allow for other optionally.

**Comment by S3D-r** [comment]
Same applies to "Support Extruder". Using another extruder for support is rare exception.

**Comment by eloipr** [comment]
Fixed! Will be available in the next release!
