### ISSUE TITLE
Centrado Mirror/Duplicate

### ISSUE THREAD

**Issue by Marcramoscosta** [BCN3D/Cura#8]
Cuando haces Mirror o Duplicate y quieres centrar la pieza en la superficie que te indica te la centra en la general

**Comment by eloipr** [comment]
En la nueva versión ya está corregido.
Te la puedes descargar aquí: [https://drive.google.com/file/d/0B9EhngnR5bl6N1Q1cXFzTkpfazQ/view](https://drive.google.com/file/d/0B9EhngnR5bl6N1Q1cXFzTkpfazQ/view)
