### ISSUE TITLE
2.0 Beta - Crashing on Slicing

### ISSUE THREAD

**Issue by 4dsystems** [BCN3D/Cura#82]
Today I am getting this alot.
I had automatic slicing enabled, but turned it off, as it was constantly showing these crashes. It doesnt close the program though after the crash, it just seems to close the engine.
Setting it back to manual slicing, it will crash after clicking prepare.
![image](https://user-images.githubusercontent.com/200210/38399522-025726cc-399f-11e8-8adf-b62df55d8fe8.png)
![image](https://user-images.githubusercontent.com/200210/38399527-08209e76-399f-11e8-9ac8-718c1b27312d.png)

**Comment by guillemavila** [comment]
Fixed https://github.com/BCN3D/BCN3DSigma-Profile-Generator/commit/48c40fcb62ce774c8cb663fe152173cb4b2565e9
