### ISSUE TITLE
When start a print job no filament comes out

### ISSUE THREAD

**Issue by Donmanfredo** [BCN3D/Cura#85]
**Application Version**
<BCN3D CURA 2.0

**Platform**
<Windows 10

When I use  both extruders on my Sigma R17  or just the right extruder, it does not start extruding in the right way. This happens only with Cura 2.0 sliced objects.

If you do a skirt, it takes till about the 3rd ring of the skirt before filament starts to flow, 
but  purging into the bin is OK. This is a bug since  the Cura 2.0 Alpha version and is still there.

**Comment by guillemavila** [comment]
Fixed ac6be0aff581c2bb717d46185720c27bda92cdb7
Thanks for reporting

**Comment by guillemavila** [comment]
Issue moved to https://github.com/BCN3D/Cura/issues/87
