### ISSUE TITLE
Crash if purge tower is turned off

### ISSUE THREAD

**Issue by JanneMantyharju** [BCN3D/Cura#89]
**Application Version**

2.0.0

**Platform**

Windows 10

**Qt**

**PyQt**

**Display Driver**

**Steps to Reproduce**

1. Load two models
2. Assign second extruder for second model
3. Merge models
4. Turn off purge tower
5. Slice

**Actual Results**

Crash

**Expected results**

No crash

**Additional Information**

**Comment by guillemavila** [comment]
Thanks for reporting, we're aware of it and will release a 2.0.1 as soon as we fix it

**Comment by guillemavila** [comment]
Related to  https://github.com/BCN3D/Cura/issues/82
