### ISSUE TITLE
Support placement issue

### ISSUE THREAD

**Issue by v-iarosenco** [BCN3D/Cura#9]
Support placement option - "touching buildplate" works as "everywhere" i.e. generates support even in places where it doesn't touch buildplate.

**Comment by guillemavila** [comment]
Yes, known bug from Cura. Change 'Support Horizontal Expansion' to 0.

Thanks for testing ;)

**Comment by v-iarosenco** [comment]
It's the same in the released 1.0.3 version. Now I know what to do, but wouldn't it be better to make it default settings?
