### ISSUE TITLE
Density of nGen filaments is set to zero

### ISSUE THREAD

**Issue by JanneMantyharju** [BCN3D/Cura#90]
Colorfabb nGen filaments have zero density which causes Cura not to calculate material usage. The density used to be correct in 2.0-beta (if I recall correctly)

Affected version: 2.0.0

**Comment by guillemavila** [comment]
Sure, fixed in in the Progen https://github.com/BCN3D/BCN3DSigma-Profile-Generator/commit/ec0ca118454c20e49987f0253b4471689af7b282
and in the profile files https://github.com/BCN3D/CuraResources/commit/040d7ed4b5c4aca28eb452f93f60a202f0352ea5
which will be included in the upcoming Cura 2.0.1
